### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by xoxoxo13102020** [erogol/TTS_recipes#4]
HEAD is now at b1935c9 update server to enable native vocoder inference and remove pwgan support
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
  File "TTS/compute_statistics.py", line 34
    print(f" > There are {len(dataset_items)} files.")
                                                    ^
SyntaxError: invalid syntax
  File "TTS/train.py", line 507
    flush=True)
         ^
SyntaxError: invalid syntax
  File "TTS/vocoder/train.py", line 444
    print(f" > Loading wavs from: {c.data_path}")
                                               ^

**I got this error what should ı do in order to make this train_model.sh file work.**

**Comment by xoxoxo13102020** [comment]
I solved it.
İf you use ubuntu you could make these changes to train_model.sh (which is in  TTS_recipes/LJSpeech/DoubleDecoderConsistency/ ) Basically you have to change python with **python3** and pip to **pip3**. And add **sudo**  keyword begining of terminal commands.

*
*
*
*


wget http://data.keithito.com/data/speech/LJSpeech-1.1.tar.bz2

tar -xjf LJSpeech-1.1.tar.bz2

shuf LJSpeech-1.1/metadata.csv > LJSpeech-1.1/metadata_shuf.csv
head -n 12000 LJSpeech-1.1/metadata_shuf.csv > LJSpeech-1.1/metadata_train.csv
tail -n 1100 LJSpeech-1.1/metadata_shuf.csv > LJSpeech-1.1/metadata_val.csv

 git clone https://github.com/mozilla/TTS

sudo apt-get install espeak
**sudo pip3 install soundfile**

cd TTS
git checkout b1935c97
**sudo pip3 install -r requirements.txt
sudo python3 setup.py install**
cd ..

**sudo python3 TTS/compute_statistics.py --config_path model_config.json --out_path ./**

CUDA_VISIBLE_DEVICES="0" python TTS/train.py --config_path model_config.json

CUDA_VISIBLE_DEVICES="0" python TTS/vocoder/train.py --config_path vocoder_config.json
