### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by xoxoxo13102020** [erogol/TTS_recipes#5]
I got some errors, I am using 
 ubuntu 18.04
 torch 1.7.0

You should know that I just download the document and  run  train_model.sh with some changes like pip3,python3 instead of pip ,python. I did not install  CUDA.

` > Using CUDA:  True
 > Number of GPUs:  1
fatal: not a git repository (or any of the parent directories): .git
 > Git Hash: 0000000
 > Experiment folder: tts_model/ljspeech-ddc-November-23-2020_03+25PM-0000000
fatal: not a git repository (or any of the parent directories): .git
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:0
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:./scale_stats.npy
 | > hop_length:256
 | > win_length:1024
 > Using model: Tacotron2

 > Model has 47914548 parameters

 > EPOCH: 0/1000

 > Number of output frames: 7

 > DataLoader initialization
 | > Use phonemes: True
   | > phoneme language: en-us
 | > Number of instances : 12969
 | > Max length sequence: 187
 | > Min length sequence: 5
 | > Avg length sequence: 98.3403500655409
 | > Num. instances discarded by max-min (max=153, min=6) seq limits: 476
 | > Batch group size: 0.

 > TRAINING (2020-11-23 15:25:04) 
 ! Run is removed from tts_model/ljspeech-ddc-November-23-2020_03+25PM-0000000
Traceback (most recent call last):
  File "TTS/train.py", line 631, in <module>
    main(args)
  File "TTS/train.py", line 546, in main
    global_step, epoch)
  File "TTS/train.py", line 149, in train
    text_input, text_lengths, mel_input, mel_lengths, speaker_ids=speaker_ids)
  File "/home/rana/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/TTS-0.0.3+b1935c9-py3.6.egg/TTS/models/tacotron2.py", line 87, in forward
    encoder_outputs = self.encoder(embedded_inputs, text_lengths)
  File "/home/rana/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/TTS-0.0.3+b1935c9-py3.6.egg/TTS/layers/tacotron2.py", line 75, in forward
    batch_first=True)
  File "/home/rana/.local/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 244, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)#değişti
**RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor**
 > Using CUDA:  True
 > Number of GPUs:  1
**fatal: not a git repository (or any of the parent directories): .git
 > Git Hash: 0000000
 > Experiment folder: vocoder_model/multiband-melgan-Kasım-23-2020_03+25ÖS-0000000**
fatal: not a git repository (or any of the parent directories): .git
 > Loading wavs from: LJSpeech-1.1/wavs/
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:0
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:scale_stats.npy
 | > hop_length:256
 | > win_length:1024
 > Generator Model: multiband_melgan_generator
 > Discriminator Model: melgan_multiscale_discriminator
 > Generator has 2539448 parameters
 > Discriminator has 4354998 parameters

 > EPOCH: 0/10000

 > TRAINING (2020-11-23 15:25:09) 
/home/rana/.local/lib/python3.6/site-packages/torch/functional.py:516: UserWarning: stft will require the return_complex parameter be explicitly  specified in a future PyTorch release. Use return_complex=False  to preserve the current behavior or return_complex=True to return  a complex output. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:653.)
  normalized, onesided, return_complex)
 ! Run is removed from vocoder_model/multiband-melgan-Kasım-23-2020_03+25ÖS-0000000
Traceback (most recent call last):
  File "TTS/vocoder/train.py", line 648, in <module>
    main(args)
  File "TTS/vocoder/train.py", line 552, in main
    epoch)
  File "TTS/vocoder/train.py", line 154, in train
    feats_real, y_hat_sub, y_G_sub)
  File "/home/rana/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/TTS-0.0.3+b1935c9-py3.6.egg/TTS/vocoder/layers/losses.py", line 233, in forward
    stft_loss_mg, stft_loss_sc = self.stft_loss(y_hat.squeeze(1), y.squeeze(1))
  File "/home/rana/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/TTS-0.0.3+b1935c9-py3.6.egg/TTS/vocoder/layers/losses.py", line 70, in forward
    lm, lsc = f(y_hat, y)
  File "/home/rana/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/TTS-0.0.3+b1935c9-py3.6.egg/TTS/vocoder/layers/losses.py", line 46, in forward
    y_hat_M = self.stft(y_hat)
  File "/usr/local/lib/python3.6/dist-packages/TTS-0.0.3+b1935c9-py3.6.egg/TTS/vocoder/layers/losses.py", line 25, in __call__
    onesided=True)
  File "/home/rana/.local/lib/python3.6/site-packages/torch/functional.py", line 516, in stft
    normalized, onesided, return_complex)
**RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!**
`

How to fix these erros?

**Comment by erogol** [comment]
it is a pytorch bug. Try a lower version. Or try to use the latest dev branch but then you might need to update some config fields.

**Comment by xoxoxo13102020** [comment]
# CUDA 10.1
`pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`

this worked for me
